#%RAML 1.0 Library
types:
  Item: !include item.raml
  putDocumentsRequest: !include workday/workdayRequest.raml
  putDocumentsResponse: !include workday/workdayResponse.raml
  callbackUrlResponse: !include response/callbackUrl.raml
  callbackUrlRequest: !include request/callbackUrl.raml
  nominationRequest: !include request/nomination.raml
  nominationResponse: !include response/nomination.raml
  signedDocumentsRequest: !include request/signedDocuments.raml
  signedDocumentsResponse: !include response/signedDocuments.raml