#%RAML 1.0 Trait
    responses:
      429:
        description: !include documentation/429-description
        body:
          application/json:
            type: !include ../../types/platformfault.raml
            example: !include ../../../examples/faults/429.json