#%RAML 1.0 Trait
    responses:
      504:
        description: !include documentation/504-description
        body:
          application/json:
            type: !include ../../types/platformfault.raml
            example: !include ../../../examples/faults/504.json